#!/bin/bash
#######################################
# voip-stack VM Manager using Lima
#
# Creates and manages Debian VMs on Apple Silicon
#
# Usage:
#   ./scripts/lima-vms.sh create    # Create all VMs
#   ./scripts/lima-vms.sh destroy   # Destroy all VMs
#   ./scripts/lima-vms.sh start     # Start all VMs
#   ./scripts/lima-vms.sh stop      # Stop all VMs
#   ./scripts/lima-vms.sh status    # Show VM status
#   ./scripts/lima-vms.sh shell <vm> # Shell into VM
#   ./scripts/lima-vms.sh inventory # Generate Ansible inventory
#######################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LIMA_DIR="$PROJECT_DIR/lima"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

check_lima() {
    if ! command -v limactl &> /dev/null; then
        error "Lima not installed. Run: brew install lima"
    fi
}

# Create Lima YAML config for a VM
create_vm_config() {
    local vm_name="$1"
    local cpus="$2"
    local memory="$3"
    local disk="$4"
    local config_file="$LIMA_DIR/${vm_name}.yaml"

    mkdir -p "$LIMA_DIR"

    cat > "$config_file" << EOF
# Lima VM configuration for $vm_name
# Generated by lima-vms.sh

# Use Debian 12 (Bookworm) ARM64
images:
  - location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-arm64.qcow2"
    arch: "aarch64"

# VM resources
cpus: $cpus
memory: "${memory}"
disk: "${disk}"

# Use QEMU with Apple Hypervisor Framework
vmType: "qemu"

# Network configuration - use user-mode networking (no root/sudo required)
networks: []

# SSH configuration
ssh:
  localPort: 0  # Auto-assign port
  loadDotSSHPubKeys: true

# Mount configuration - minimal for server VMs
mounts: []

# Provision script - basic setup
provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux

      # Update and install essentials
      apt-get update
      apt-get install -y curl wget vim htop net-tools dnsutils python3 python3-apt

      # Set hostname
      hostnamectl set-hostname $vm_name

      echo "VM $vm_name provisioned successfully"

# Message shown after VM starts
message: |
  VM '$vm_name' is ready!

  Shell access: limactl shell $vm_name
  SSH access:   ssh -F ~/.lima/$vm_name/ssh.config lima-$vm_name
EOF

    echo "$config_file"
}

cmd_create() {
    check_lima
    info "Creating VoIP VMs with Debian 12..."

    # VM definitions: name cpus memory disk
    local vms=(
        "sip-1 2 2GiB 20GiB"
        "media-1 4 4GiB 20GiB"
        "pbx-1 2 4GiB 20GiB"
    )

    for vm_spec in "${vms[@]}"; do
        read -r vm_name cpus memory disk <<< "$vm_spec"

        if limactl list -q 2>/dev/null | grep -q "^${vm_name}$"; then
            warn "VM $vm_name already exists, skipping"
        else
            info "Creating $vm_name (cpus=$cpus, mem=$memory, disk=$disk)..."
            local config_file=$(create_vm_config "$vm_name" "$cpus" "$memory" "$disk")
            limactl create --name="$vm_name" "$config_file"
            limactl start "$vm_name"
            success "Created and started $vm_name"
        fi
    done

    echo ""
    cmd_status
}

cmd_destroy() {
    check_lima
    warn "This will destroy all VoIP VMs!"
    read -p "Are you sure? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        for vm_name in sip-1 media-1 pbx-1; do
            if limactl list -q 2>/dev/null | grep -q "^${vm_name}$"; then
                info "Destroying $vm_name..."
                limactl stop "$vm_name" 2>/dev/null || true
                limactl delete "$vm_name"
                success "Destroyed $vm_name"
            fi
        done
        # Clean up config files
        rm -f "$LIMA_DIR"/*.yaml 2>/dev/null || true
    else
        info "Cancelled"
    fi
}

cmd_start() {
    check_lima
    info "Starting VMs..."
    for vm_name in sip-1 media-1 pbx-1; do
        if limactl list -q 2>/dev/null | grep -q "^${vm_name}$"; then
            limactl start "$vm_name" 2>/dev/null || true
            success "Started $vm_name"
        else
            warn "VM $vm_name doesn't exist"
        fi
    done
}

cmd_stop() {
    check_lima
    info "Stopping VMs..."
    for vm_name in sip-1 media-1 pbx-1; do
        if limactl list -q 2>/dev/null | grep -q "^${vm_name}$"; then
            limactl stop "$vm_name" 2>/dev/null || true
            success "Stopped $vm_name"
        fi
    done
}

cmd_status() {
    check_lima
    echo -e "${BLUE}═══ voip-stack VM Status (Lima/Debian) ═══${NC}"
    echo ""

    limactl list 2>/dev/null || echo "No VMs found"

    echo ""
    echo -e "${BLUE}Shell Access:${NC}"
    echo "  limactl shell sip-1"
    echo "  limactl shell media-1"
    echo "  limactl shell pbx-1"
    echo ""
    echo -e "${BLUE}SSH Access:${NC}"
    for vm_name in sip-1 media-1 pbx-1; do
        if limactl list -q 2>/dev/null | grep -q "^${vm_name}$"; then
            local ssh_config="$HOME/.lima/$vm_name/ssh.config"
            if [[ -f "$ssh_config" ]]; then
                echo "  ssh -F $ssh_config lima-$vm_name"
            fi
        fi
    done
}

cmd_shell() {
    check_lima
    local vm_name="${1:-}"
    if [[ -z "$vm_name" ]]; then
        echo "Usage: $0 shell <vm-name>"
        echo "Available VMs: sip-1, media-1, pbx-1"
        exit 1
    fi
    limactl shell "$vm_name"
}

cmd_inventory() {
    check_lima
    info "Generating Ansible inventory..."

    local inventory_file="$PROJECT_DIR/ansible/inventory/lima.yml"

    cat > "$inventory_file" << 'HEADER'
# Ansible inventory for Lima VMs (Debian 12)
# Auto-generated by lima-vms.sh
#
# Usage:
#   ansible-playbook -i inventory/lima.yml playbooks/provision-vms.yml

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

    # DevStack Core integration
    # Lima VMs can reach host via gateway
    devstack_host: "{{ ansible_default_ipv4.gateway | default('host.lima.internal') }}"
    vault_addr: "http://{{ devstack_host }}:8200"
    postgres_host: "{{ devstack_host }}"
    redis_host: "{{ devstack_host }}"
    rabbitmq_host: "{{ devstack_host }}"

    # Domain configuration
    domain: sip.local

  children:
    voip:
      children:
        sip_proxies:
          hosts:
HEADER

    # Add sip-1
    if limactl list -q 2>/dev/null | grep -q "^sip-1$"; then
        local ssh_config="$HOME/.lima/sip-1/ssh.config"
        cat >> "$inventory_file" << EOF
            sip-1:
              ansible_host: lima-sip-1
              ansible_ssh_common_args: '-F $ssh_config'
              ansible_user: "$USER"
              internal_ip: "{{ ansible_default_ipv4.address }}"
              has_external_interface: true
              opensips_enabled: true
              kamailio_enabled: false

EOF
    fi

    cat >> "$inventory_file" << 'MEDIA_HEADER'
        media_servers:
          hosts:
MEDIA_HEADER

    # Add media-1
    if limactl list -q 2>/dev/null | grep -q "^media-1$"; then
        local ssh_config="$HOME/.lima/media-1/ssh.config"
        cat >> "$inventory_file" << EOF
            media-1:
              ansible_host: lima-media-1
              ansible_ssh_common_args: '-F $ssh_config'
              ansible_user: "$USER"
              internal_ip: "{{ ansible_default_ipv4.address }}"
              has_external_interface: true
              rtpengine_enabled: true

EOF
    fi

    cat >> "$inventory_file" << 'PBX_HEADER'
        pbx:
          hosts:
PBX_HEADER

    # Add pbx-1
    if limactl list -q 2>/dev/null | grep -q "^pbx-1$"; then
        local ssh_config="$HOME/.lima/pbx-1/ssh.config"
        cat >> "$inventory_file" << EOF
            pbx-1:
              ansible_host: lima-pbx-1
              ansible_ssh_common_args: '-F $ssh_config'
              ansible_user: "$USER"
              internal_ip: "{{ ansible_default_ipv4.address }}"
              has_external_interface: false
              asterisk_enabled: true
              freeswitch_enabled: false
EOF
    fi

    success "Generated $inventory_file"
    echo ""
    cat "$inventory_file"
}

cmd_help() {
    cat << 'EOF'
voip-stack VM Manager (Lima/Debian)

Usage: ./scripts/lima-vms.sh <command> [options]

Commands:
  create              Create all VMs (sip-1, media-1, pbx-1)
  destroy             Destroy all VMs (with confirmation)
  start               Start all VMs
  stop                Stop all VMs
  status              Show VM status
  shell <vm>          Shell into specific VM
  inventory           Generate Ansible inventory file
  help                Show this help message

Examples:
  ./scripts/lima-vms.sh create
  ./scripts/lima-vms.sh status
  ./scripts/lima-vms.sh shell sip-1
  ./scripts/lima-vms.sh inventory

VM Specifications (Debian 12 Bookworm ARM64):
  sip-1:    2 CPUs, 2GB RAM, 20GB disk (OpenSIPS)
  media-1:  4 CPUs, 4GB RAM, 20GB disk (RTPEngine)
  pbx-1:    2 CPUs, 4GB RAM, 20GB disk (Asterisk)

After creating VMs, generate inventory and run Ansible:
  ./scripts/lima-vms.sh inventory
  ansible-playbook -i ansible/inventory/lima.yml ansible/playbooks/provision-vms.yml

EOF
}

# Main
main() {
    local command="${1:-help}"
    shift || true

    case "$command" in
        create)     cmd_create ;;
        destroy)    cmd_destroy ;;
        start)      cmd_start ;;
        stop)       cmd_stop ;;
        status)     cmd_status ;;
        shell)      cmd_shell "$@" ;;
        inventory)  cmd_inventory ;;
        help|--help|-h) cmd_help ;;
        *)
            error "Unknown command: $command. Use 'help' for usage."
            ;;
    esac
}

main "$@"
