#!/bin/bash
#######################################
# voip-stack VM Manager using Multipass
#
# Creates and manages VoIP VMs on Apple Silicon
#
# Usage:
#   ./scripts/multipass-vms.sh create    # Create all VMs
#   ./scripts/multipass-vms.sh destroy   # Destroy all VMs
#   ./scripts/multipass-vms.sh start     # Start all VMs
#   ./scripts/multipass-vms.sh stop      # Stop all VMs
#   ./scripts/multipass-vms.sh status    # Show VM status
#   ./scripts/multipass-vms.sh ssh <vm>  # SSH into VM
#######################################

set -euo pipefail

# VM Definitions
declare -A VMS=(
    ["sip-1"]="cpus=2,mem=2G,disk=20G"
    ["media-1"]="cpus=4,mem=4G,disk=20G"
    ["pbx-1"]="cpus=2,mem=4G,disk=20G"
)

# Ubuntu version (22.04 LTS has good ARM64 support)
UBUNTU_VERSION="22.04"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

check_multipass() {
    if ! command -v multipass &> /dev/null; then
        error "Multipass not installed. Run: brew install --cask multipass"
    fi
}

cmd_create() {
    check_multipass
    info "Creating VoIP VMs..."

    for vm_name in "${!VMS[@]}"; do
        local config="${VMS[$vm_name]}"
        local cpus=$(echo "$config" | grep -o 'cpus=[^,]*' | cut -d= -f2)
        local mem=$(echo "$config" | grep -o 'mem=[^,]*' | cut -d= -f2)
        local disk=$(echo "$config" | grep -o 'disk=[^,]*' | cut -d= -f2)

        if multipass info "$vm_name" &>/dev/null; then
            warn "VM $vm_name already exists, skipping"
        else
            info "Creating $vm_name (cpus=$cpus, mem=$mem, disk=$disk)..."
            multipass launch "$UBUNTU_VERSION" \
                --name "$vm_name" \
                --cpus "$cpus" \
                --memory "$mem" \
                --disk "$disk"
            success "Created $vm_name"
        fi
    done

    # Show status and IPs
    echo ""
    cmd_status
}

cmd_destroy() {
    check_multipass
    warn "This will destroy all VoIP VMs!"
    read -p "Are you sure? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        for vm_name in "${!VMS[@]}"; do
            if multipass info "$vm_name" &>/dev/null; then
                info "Destroying $vm_name..."
                multipass delete "$vm_name" --purge
                success "Destroyed $vm_name"
            fi
        done
    else
        info "Cancelled"
    fi
}

cmd_start() {
    check_multipass
    info "Starting VMs..."
    for vm_name in "${!VMS[@]}"; do
        if multipass info "$vm_name" &>/dev/null; then
            multipass start "$vm_name"
            success "Started $vm_name"
        else
            warn "VM $vm_name doesn't exist"
        fi
    done
}

cmd_stop() {
    check_multipass
    info "Stopping VMs..."
    for vm_name in "${!VMS[@]}"; do
        if multipass info "$vm_name" &>/dev/null; then
            multipass stop "$vm_name"
            success "Stopped $vm_name"
        fi
    done
}

cmd_status() {
    check_multipass
    echo -e "${BLUE}═══ voip-stack VM Status ═══${NC}"
    echo ""

    # Table header
    printf "%-12s %-10s %-16s %-6s %-6s\n" "NAME" "STATE" "IP" "CPUS" "MEM"
    printf "%-12s %-10s %-16s %-6s %-6s\n" "----" "-----" "--" "----" "---"

    for vm_name in sip-1 media-1 pbx-1; do
        if multipass info "$vm_name" &>/dev/null; then
            local state=$(multipass info "$vm_name" --format csv | tail -1 | cut -d, -f2)
            local ip=$(multipass info "$vm_name" --format csv | tail -1 | cut -d, -f3)
            local cpus=$(multipass info "$vm_name" --format csv | tail -1 | cut -d, -f4)
            local mem=$(multipass info "$vm_name" --format csv | tail -1 | cut -d, -f6)
            printf "%-12s %-10s %-16s %-6s %-6s\n" "$vm_name" "$state" "${ip:-N/A}" "$cpus" "$mem"
        else
            printf "%-12s %-10s %-16s %-6s %-6s\n" "$vm_name" "not found" "-" "-" "-"
        fi
    done

    echo ""
    echo -e "${BLUE}SSH Access:${NC}"
    echo "  multipass shell sip-1"
    echo "  multipass shell media-1"
    echo "  multipass shell pbx-1"
}

cmd_ssh() {
    check_multipass
    local vm_name="${1:-}"
    if [[ -z "$vm_name" ]]; then
        echo "Usage: $0 ssh <vm-name>"
        echo "Available VMs: sip-1, media-1, pbx-1"
        exit 1
    fi
    multipass shell "$vm_name"
}

cmd_inventory() {
    check_multipass
    info "Generating Ansible inventory..."

    local inventory_file="${SCRIPT_DIR}/../ansible/inventory/multipass.yml"

    cat > "$inventory_file" << 'HEADER'
# Ansible inventory for Multipass VMs
# Auto-generated by multipass-vms.sh
#
# Usage:
#   ansible-playbook -i inventory/multipass.yml playbooks/provision-vms.yml

all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

    # DevStack Core integration (host machine)
    # Multipass VMs can reach host via the bridge IP
    devstack_host: "{{ ansible_default_ipv4.gateway }}"
    vault_addr: "http://{{ devstack_host }}:8200"
    postgres_host: "{{ devstack_host }}"
    redis_host: "{{ devstack_host }}"
    rabbitmq_host: "{{ devstack_host }}"

    # Domain configuration
    domain: sip.local

  children:
    voip:
      children:
        sip_proxies:
          hosts:
HEADER

    # Add sip-1
    if multipass info sip-1 &>/dev/null; then
        local sip_ip=$(multipass info sip-1 --format csv | tail -1 | cut -d, -f3)
        cat >> "$inventory_file" << EOF
            sip-1:
              ansible_host: $sip_ip
              internal_ip: $sip_ip
              has_external_interface: true
              opensips_enabled: true
              kamailio_enabled: false

EOF
    fi

    cat >> "$inventory_file" << 'MEDIA_HEADER'
        media_servers:
          hosts:
MEDIA_HEADER

    # Add media-1
    if multipass info media-1 &>/dev/null; then
        local media_ip=$(multipass info media-1 --format csv | tail -1 | cut -d, -f3)
        cat >> "$inventory_file" << EOF
            media-1:
              ansible_host: $media_ip
              internal_ip: $media_ip
              has_external_interface: true
              rtpengine_enabled: true

EOF
    fi

    cat >> "$inventory_file" << 'PBX_HEADER'
        pbx:
          hosts:
PBX_HEADER

    # Add pbx-1
    if multipass info pbx-1 &>/dev/null; then
        local pbx_ip=$(multipass info pbx-1 --format csv | tail -1 | cut -d, -f3)
        cat >> "$inventory_file" << EOF
            pbx-1:
              ansible_host: $pbx_ip
              internal_ip: $pbx_ip
              has_external_interface: false
              asterisk_enabled: true
              freeswitch_enabled: false
EOF
    fi

    success "Generated $inventory_file"
    cat "$inventory_file"
}

cmd_help() {
    cat << 'EOF'
voip-stack VM Manager (Multipass)

Usage: ./scripts/multipass-vms.sh <command> [options]

Commands:
  create              Create all VMs (sip-1, media-1, pbx-1)
  destroy             Destroy all VMs (with confirmation)
  start               Start all VMs
  stop                Stop all VMs
  status              Show VM status and IP addresses
  ssh <vm>            SSH into specific VM
  inventory           Generate Ansible inventory file
  help                Show this help message

Examples:
  ./scripts/multipass-vms.sh create
  ./scripts/multipass-vms.sh status
  ./scripts/multipass-vms.sh ssh sip-1
  ./scripts/multipass-vms.sh inventory

VM Specifications:
  sip-1:    2 CPUs, 2GB RAM, 20GB disk (OpenSIPS)
  media-1:  4 CPUs, 4GB RAM, 20GB disk (RTPEngine)
  pbx-1:    2 CPUs, 4GB RAM, 20GB disk (Asterisk)

After creating VMs, generate inventory and run Ansible:
  ./scripts/multipass-vms.sh inventory
  ansible-playbook -i ansible/inventory/multipass.yml ansible/playbooks/provision-vms.yml

EOF
}

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Main
main() {
    local command="${1:-help}"
    shift || true

    case "$command" in
        create)     cmd_create ;;
        destroy)    cmd_destroy ;;
        start)      cmd_start ;;
        stop)       cmd_stop ;;
        status)     cmd_status ;;
        ssh)        cmd_ssh "$@" ;;
        inventory)  cmd_inventory ;;
        help|--help|-h) cmd_help ;;
        *)
            error "Unknown command: $command. Use 'help' for usage."
            ;;
    esac
}

main "$@"
